name: AWS CI/CD

on:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: touch .env

      - name: Populate .env with secrets
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Restart the app
        run: |
          /home/ubuntu/.nvm/versions/node/v22.19.0/bin/pm2 restart app || /home/ubuntu/.nvm/versions/node/v22.19.0/bin/pm2 start index.js --name app
